name: "Sharon Grossman"
description: "The Personal Homepage for Sharon Grossman"

url: "http://sharonrgrossman.com"

gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true
